spring.application.name=lecture

# 서버 포트
server.port=8282

# H2 DATABASE 추후 test-properties로 이관
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

# Devtools: 변경즉시반영
spring.devtools.livereload.enabled=true

# File upload path 설정
file.upload-dir=C:/lecture/class/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Maria db 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# Spring security 초기 설정 (build.gradle상의 dependency 주석 처리로 disable가능 or Security config permit 설정)
spring.security.user.name=admin
spring.security.user.password=admin123
